#!/usr/bin/env bash
# show redirection in nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' > /var/www/html/index.html
new_string="root /var/www/html;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
string_to_replace="root /var/www/html;"
sed -i "s|${string_to_replace}|${new_string}|" /etc/nginx/sites-enabled/default
service nginx reload
