#!/usr/bin/env bash

# Define variables
WEBSITE_CONTENT_DIR="/var/www/html"
WEBSITE_INDEX_FILE="$WEBSITE_CONTENT_DIR/index.html"
WEBSITE_404_FILE="$WEBSITE_CONTENT_DIR/404.html"
NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"

# Define functions
install_dependencies()
{
    apt-get update
    apt-get install -y nginx
}

create_website_content()
{
    mkdir -p "$WEBSITE_CONTENT_DIR"
    echo "Hello world" > "$WEBSITE_INDEX_FILE"
    echo "Ceci n'est pas une page" > "$WEBSITE_404_FILE"
}

configure_nginx()
{
    cat > "$NGINX_CONFIG_FILE" <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root $WEBSITE_CONTENT_DIR;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
        root $WEBSITE_CONTENT_DIR;
        internal;
    }
}
EOF

    # Restart Nginx to apply new configuration
    service nginx restart
}

# Call functions
install_dependencies
create_website_content
configure_nginx




























